language: cpp

sudo: required

services:
  - docker
  
env:
  - MODE=build
  - MODE=test
  
matrix:
  allow_failures:
    - env: MODE=test
  
git:
  submodules: false

compiler:
  - gcc
  - clang

before_install:
  - docker pull kokutoru/gtox-travis-build

script:
  - cd src && mkdir build
  - docker run -v $PWD:/opt/gtox kokutoru/gtox-travis-build bash -c "cd /opt/gtox/build && CXX=$CXX cmake –GNinja .."
  - docker run -v $PWD:/opt/gtox kokutoru/gtox-travis-build bash -c "cd /opt/gtox/build && make"
  - docker run -v $PWD:/opt/gtox kokutoru/gtox-travis-build bash -c "cd /opt/gtox/build && ./tox/toxmm-test"

