language: cpp

sudo: required

services:
  - docker

matrix:
  include:
    - compiler: gcc
      env: DOCKER=kokutoru/gtox-travis-build CMAKE=cmake TEST=0
    - compiler: clang
      env: DOCKER=kokutoru/gtox-travis-build CMAKE=cmake TEST=0
    - compiler: gcc
      env: DOCKER=kokutoru/gtox-travis-build CMAKE=cmake TEST=1
    - compiler: clang
      env: DOCKER=kokutoru/gtox-travis-build CMAKE=cmake TEST=1
    - compiler: gcc
      env: DOCKER=kokutoru/gtox-travis-build-mingw-w64 CMAKE=x86_64-w64-mingw32-cmake TEST=0
  allow_failures:
    - env: DOCKER=kokutoru/gtox-travis-build CMAKE=cmake TEST=1

git:
  submodules: false

before_install:
  - docker pull $DOCKER

script:
  - cd src && mkdir build
  - docker run -v $PWD:/opt/gtox $DOCKER bash -c "cd /opt/gtox/build && CXX=$CXX $CMAKE –GNinja .."
  - docker run -v $PWD:/opt/gtox $DOCKER bash -c "cd /opt/gtox/build && make"
  - if [ $TEST == 1 ]; then docker run -v $PWD:/opt/gtox $DOCKER bash -c "cd /opt/gtox/build && ./tox/toxmm-test"; fi

